### ISSUE TITLE
Report type of special cause variation

### ISSUE THREAD

**Issue by richard28nhs** [nhs-r-community/NHSRplotthedots#122]
As a user I want to know why a point is displaying special cause variation, which rule has it met?

This could be captured in the final df as a column, or a series of columns. 

It could then be displayed as a tooltip, summary table or in text r.  

Looking at the code, I think ptd_calculate_point_type.R generates  the necessary information and something like this

ptd_special_cause_text<- function(y, relative_to_mean, close_to_limits, outside_limits) {
  part_seven_point_one_side_mean <- ptd_part_of_seven_trend(ptd_seven_point_one_side_mean(relative_to_mean))
  part_seven_point_trend <- ptd_part_of_seven_trend(ptd_seven_point_trend(y))
  part_two_in_three <- ptd_part_of_two_in_three(ptd_two_in_three(close_to_limits), close_to_limits)

case_when 
      outside_limits== 1 ~ 'Outside limits'  ,
      part_seven_point_trend== 1 ~ 'Trend' ,
      part_seven_point_one_side_mean == 1~ 'Run above mean' ,
      part_two_in_three == 1~ 'Two out three close to outlier limits',
     TRUE ~ "NA") 
  )
}

Need a bit of  user engagement on the text t o use and primacy of rules

**Comment by tomjemmett** [comment]
so originally it did sort of do this by introducing multiple columns (one per rule), then an overall column. This wasn't particularly easy to test, so each rule was turned into a pure function, and then we have one function that run's all of the "rules" and returns a binary yes/no value. I would like to maintain the pure functions for that testability rather than one long  statement.

Part of the issue is we can either:
* a) allow only one rule (potentially a point could be triggered by multiple rules). We would need to define a hierarchy of "importance" of the rules and know how to avoid confusion (imagine we have a run above the mean, but point 3 is outside the limits and points 4 and 6 and two out of three close to outer limits... how should this display? ccabcbc? ccacccc?) 
* b) show all of the rules that were triggered

If b, there are a couple of things we could do here:
1) introduce columns for each rule, I think this is a messy approach as the data frame becomes large
2) instead of making the column binary, turn it into a bit field (each rule is some value 2^n), that way we can simple bitwise OR all of the values, if the value is non-zero then we know the rules have been violated. This could then have a custom class which handles the printing (it converts x & 2^0 to "Rule 1", x & 2^1 to "Rule 2" (so on and so forth)
3) similar to 2, but we instead turn each rule into a string, and store that in a list column in the dataframe, if we built this using the {vctrs} package it could look very neat in the output of `as.tibble(ptd_spc(data))`
4) like 3, but instead of doing something fancy we simply return a comma separated string. While this is simple, it has the effect of making "an,exceptionally,long,string", which if you were to convert to a data.frame instead of a tibble will print out terribly

personally I prefer b (in my mind, either we completely summarise the information or we don't summarise at all). Of the options 3 probably sounds most sensible, but adds an extra dependency, and does cause additional data storage (though, with string interning it should be negligible). I'll try to draft something in {vctrs}
