### ISSUE TITLE
Throw a warning or error when incomplete dataset is passed in by mistake

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#138]
Currently no error is thrown in the situation below.  It's a situation that could happen when filtering from a larger dataset, and missing counts are not replaced with zeros, or rejoined to the original date range.
An error would draw attention to the problem.

```r
set.seed(3)
date <- seq.Date(from = as.Date("2020-01-01"), by = "month", length.out = 20)
data <- rnorm(20)

dtf <- data.frame(date, data)
dtf <- dtf[-c(5, 10,11,12), ] # simulate missing rows of data

ptd_spc(dtf, data, date)
```
![image](https://user-images.githubusercontent.com/10871342/144636202-8bb108a7-9f73-48f9-9630-24582d6c66dd.png)

**Comment by tomjemmett** [comment]
I've tried to solve a problem like this in the past and gave up... the difficulty is if you are using a date axis, as there number of units between points can vary... if you are showing daily, or weekly then you have a consistent step of 1 and 7. But if it's monthly then you need to check if the step is one of 30, 31, 28, 29...

you could build something pretty hacky to try to handle this (dx is roughly mean dx), because hardcoding time steps like above is going to be problematic (what if you have quarterly data? or some weird time unit like every other month?)

**Comment by LynHoward** [comment]
Would you want an error thrown or a break in the line? Or both?

**Comment by ThomUK** [comment]
Initially I thought erroring would be best because I don't think the xmr maths is valid with missing points. 

Tolerating missing points with a warning might be an option, as long as the gaps in the data are treated properly. Gaps should probably break not probably sustain a special cause signal, for example. Would welcome other views on that - it could be dangerous ground.

The error would be easiest to implement, and it also forces the decision of how to handle missing points back to the user.  I was thinking of using a hacky method along the lines of what Tom mentioned.

**Comment by johnmackintosh** [comment]
It wouldn't necessarily be accurate to replace missings with zero 
The chart looks at the variation between points, and, as far as I'm aware, a 'gap' between points doesn't affect the math.
However, my memory of the theory behind this chart is like flecks of pollen on a mouse's handkerchief, so I will look into it later.
For a single chart, it's not a problem.
For a faceted chart, I'd be tempted to let ggplot2 do it's thing and let the user over-ride that as they see fit.

**Comment by LynHoward** [comment]
I would insert the missing dates & allow coercion to set the data values as NA, so that ggplot includes breaks in the line. The interval could be set by the difference between the 1st & 2nd dates, but that seems to be unnecessarily creating work! 

 alldates <- seq(min(date), max(date), by = params$interval)

**Comment by tomjemmett** [comment]
In terms of the maths behind - it only uses the y-values, ignoring the x-values (other than for ordering y).

As for inserting NA's: we have a filter to explicitly error if any NA values occur, so that won't help here. And implicit conversion of the data feels like the wrong approach to me.

We could argue that this isn't a package for data validation, it's the users job to check for sanity. If we implement a rule for this data validation, then are there other things we should check for. Of the top of my head, what about "outliers"... that feels like a bit of a slippery slope. So, perhaps instead of providing some warning here, we could just document how to resolve (e.g. using [`tidyr::complete()`](https://tidyr.tidyverse.org/reference/complete.html)).

**Comment by LynHoward** [comment]
I know that Tom's original issue was in regard of incomplete datasets by mistake, but this is a feature I will need for the many occasions when I'll know that I have incomplete data (for example, 5 trusts will be moving to new EPR systems within a year). 

What's the risk here with implicit conversion and what would you suggest instead? Using complete() would only add existing dates, not infill those completely missing in the original dataset. Or were you meaning in conjunction with seq() to create the missing dates?

I'm happy to work on this if it would be useful to someone other than just me!

**Comment by ThomUK** [comment]
Having put some thought into this, I'm thinking of closing this issue.  

I have come to the view that knowing the data going in is more important than this package warning the user of gaps.  The gaps are visible in the plot, so the user can choose what to do to handle them, and leaving this error message out of the package would give them the most flexibility to handle them in the best way for their data.

**Comment by ThomUK** [comment]
Closing for the reasons above.
