### ISSUE TITLE
Consider changing the rebase API for ease of use

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#42]
At the moment, rebasing involves adding a column to the dataframe with 1 against the date to rebase. Applying it happens by calling `rebase = "name_of_rebase_column"`

For ease of use, could we consider implementing something like:
`rebase = c("2020-01-01", "2021-02-01")`
Where the strings passed in can be coerced to dates and used internally to create the rebase column (in this case, two rebases). That method may be easier for users who are processing a handful of charts, or driving the configuration of their charts from a KPI index table or master sheet.

For backward compatibility it may be possible to use both APIs. If a string is passed in,  interpret it as a column name for an existing rebase column. If a vector is passed in, coerce it to date(s) and use internally to create the rebase column.

This is perhaps something for after the current flurry of activity.

**Comment by tomjemmett** [comment]
Regarding backward compatibility: I think we are early enough on the journey to make breaking changes without worry!

**Comment by chrisreading01** [comment]
Feeding in a vector of dates was the original way the function worked in my oldest code. I think the reason that I switched to a rebase field was so that, if faceting, the function could account for different facets being rebased at different points in time. On that basis, I would prefer the option to feed either a date string or a field name. If the former, then every facet would be rebased at the same dates. If a field name, then the user has the option to have different facets rebasing at different intervals. What do you think? 

From an implementation perspective, it's probably simplest to have the date string generate an integer column so that the rest of the spcStandard() function works in the same way.

**Comment by ThomUK** [comment]
Good point, I hadn't thought about facets because I don't often use them.

My use-case will be to run individual calls to spc() in a loop, with the specification for each KPI pulled from one dataframe (title, axis specs, source caption, baseline period, rebase dates, etc), and the data pulled from another (or queried live).

I'm happy to hand-roll something in my report loop if my use-case is a bit weird and wouldn't be useful for others. I'm using it because I can run 50 full-size charts in one go (and hopefully later fold them into a javascript/html drop-down with variation, assurance, and data quality icons still visible above the fold).

**Comment by tomjemmett** [comment]
I would probably argue that with facet's all plots should have the same basis for their calculations - if you wanted different rebasing for different plots then they should be drawn separately. By putting all of the plots on the same image there is a suggestion that they are all calculated identically.

**Comment by chrisreading01** [comment]
I can see your point @tomjemmett, for some of the uses I can imagine in our performance team I would prefer to still have the option to vary the rebase but perhaps automatically add a caveat if you have differences in rebase periods. Our performance manager looks at metrics like cancer 2WW performance with a specialty level faceting. If there was a decision to rebase in a single cancer specialty, because of a known intervention or pathway change, he would still want to see them collectively and caveat that a specific decision to rebase was made for that specialty.

**Comment by tomjemmett** [comment]
I've made a quick branch to explore how we could solve this using a helper method, `ptd_rebase()`, this can either accept a vector of dates (will rebase all facets with those dates), or, you can name each vector of dates using the name of the facet to individual facet. See [rebase_api](https://github.com/nhs-r-community/NHSRplotthedots/tree/rebase_api) branch. Would love to get some feedback to this (the documentation is pretty rubbish at the moment mind!)

I think this same kind of logic could be applied to the target field if we like this approach
