### ISSUE TITLE
add a legend to the bottom of the plot in similar style to excel output

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#58]
Consider adding a legend to the bottom of the plot to provide a similar visual "quick reference guide" for people who do not interpret SPC plots all the time.  

As with the other plot elements, it would be ideal if it looked similar to the excel output:
(not a great example plot because it hasn't been baselined, but the legend is the same for all plots)
![Excel plot - current](https://user-images.githubusercontent.com/10871342/126877639-6b4f1ea2-ec1c-4eb5-856a-4738a4ccf62f.PNG)

This issue was originally part of #8.

**Comment by tomjemmett** [comment]
Without intending to sound pedantic, I think what you are after here is a key, not a legend.

The difference here being ggplot can produce a legend, but I don't think you can produce a key.

In order to use a legend we would have to change the way we generate the chart and possibly the data before creating the chart. E.g. instead of having a column indicating whether a point is special cause etc. we should have a table of points and map the colour aesthetic. This will be slightly more tricky with the upl/lpl etc. lines, but it could probably be achieved by pivot longer and then mapping the group aesthetic to the "key" column.

**Comment by chrismainey** [comment]
Can we check the text corresponds to plot the dots here?

**Comment by tomjemmett** [comment]
see #51 - there is a clip from the PTD stuff and to me this matches there text (in a condensed form at least)
