### ISSUE TITLE
All y axis percentages end with decimal zero

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#87]
Ideally, this would only be the case if the decimal is non-zero.  
Current state:
![image](https://user-images.githubusercontent.com/10871342/134425621-f600fc62-1322-4c70-baf8-f7b4d6432ebb.png)

**Comment by tomjemmett** [comment]
I think this could start becoming messy, at the moment we just leave the handling to `scales::percent_format()`, with a default value of 0.1 for accuracy. Seems like a reasonable compromise when we aren't looking at what a good value would be. [code](https://github.com/nhs-r-community/NHSRplotthedots/blob/5e8f5176edcb7e18d82a401e054a10284abb22e1/R/ptd_create_ggplot.R#L149)

We do though have an argument to control this in `y_axis_breaks` (which is probably the wrong name for this argument...)

My vote would be to [keep our stuff simple](https://en.m.wikipedia.org/wiki/KISS_principle) but allow people to control things using normal ggplot2 stuff if they want some further customisation

**Comment by ThomUK** [comment]
I agree with the KISS principle, but many people are going to be maintaining the code to do this outside of the package, if we don't put it in.  I'm happy to do the research and write the code - probably conditionally assigning the 0.1 value based on the axis limits.  I'm happy to self-assign this and make a draft PR for review.

**Comment by tomjemmett** [comment]
We could try to just remove this argument from percent_format, and let it handle things. Otherwise it's a case of trying to figure out what the scale is going to be and then choosing an appropriate accuracy... that feels like hard work, and a duplication of what ggplot does for you.

Another option maybe to change the default to 1, so we default to 90%, 91% etc. this of course fails if ggplot picks a scale like 90%, 92.5%, (we would probably get 90, 92, 95, 98...)
